spring.application.name=7ch

# DB接続設定
spring.datasource.url=jdbc:postgresql://localhost:5432/7ch-postgres
spring.datasource.username=shink
spring.datasource.password=515

logging.level.org.springframework.security=DEBUG